---
# tasks file for reinstall_packages

- name: "V-71855 get all files needed for package reinstall..."
  shell: rpm -Va | grep '^..5'
  register: rsp
  ignore_errors: True
  tags:
    - reinstall_setup

- name: "V-71855 parse out the file paths..."
  set_fact:
      var2: "{{ item | regex_search('(/etc.*)') }}"
      allfiles: "{{ allfiles }} + ['{{ var2 }}']"
  with_items:
     - "{{ rsp.stdout_lines }}"
  ignore_errors: True
  tags:
    - reinstall_setup

- name: "V-71855 list the packages needed for each file to reinstall"
  shell: "rpm -qf {{ item }}"
  register: rsp
  with_items:
     - "{{ allfiles }}"
  ignore_errors: True
  tags:
    - reinstall_setup

- name: "V-71855 parse out the package names for the rpm output"
  set_fact:
      allpack: "{{ allpack }} {{ item.stdout }}"
  with_items:
     - "{{ rsp.results }}"
  ignore_errors: True
  tags:
    - reinstall_setup

- debug: msg="{{ allpack }}"
  tags:
    - reinstall_setup

- name: "V-71855 reinstall all packages..."
  script: reinstall.py "{{ allpack }}"
  register: resp
  ignore_errors: True
  tags:
    - reinstall_setup

- debug: msg="{{ resp.stdout_lines }}"
  tags:
    - reinstall_setup

...

