---
# tasks file for aide_config

- name: "V-72069, V-72071, V-72073 -- Configure All value in /etc/aide.conf"
  blockinfile:
     path: /etc/aide.conf
     create: yes
     block: |
         All= p+i+n+u+g+s+m+S+sha512+acl+xattrs+selinux
         /bin All
         /sbin All
  ignore_errors: yes
  tags:
    - aide_setup
    - '72069'

- name: "V-71975 -- create /etc/cron.daily/aide..."
  file:
    path: /etc/cron.daily/aide
    state: touch
    mode: 0700
  ignore_errors: yes
  tags:
    - misc_setup
    - '71975'

- name: "V-71973 -- add line to  /etc/cron.daily/aide..."
  lineinfile:
    path: /etc/cron.daily/aide
    line: '0 0 * * * /usr/sbin/aide --check'
  ignore_errors: yes
  tags:
    - misc_setup
    - '71973'
...

