---
# tasks file for gui_config

- name: "V-xxxx -- create /etc/dconf/db/local.d/01-banner-message..."
  file:
    path: /etc/dconf/db/local.d/01-banner-message
    state: touch
  ignore_errors: yes
  tags:
    - gui_setup
    - 'xxxxx'

- name: "V-xxxxx -- add banner message for GUI ..."
  blockinfile:
     path: /etc/dconf/db/local.d/01-banner-message
     block: |
          [org/gnome/login-screen]
          banner-message-enable=true
          banner-message-text='You are accessing '
  ignore_errors: yes
  tags:
    - gui_setup
    - 'xxxxx'


- name: "V-xxxx -- create /etc/dconf/db/local.d/00-screensaver..."
  file:
    path: /etc/dconf/db/local.d/00-screensaver
    state: touch
  ignore_errors: yes
  tags:
    - gui_setup
    - 'xxxxx'

- name: "V-xxxxx -- setup screensaver data to 00-screensaver file..."
  blockinfile:
     path: /etc/dconf/db/local.d/00-screensaver
     block: |
          [org/gnome/desktop/screensaver]
          lock-enabled=true
          lock-delay=uint32 5
          idle-activation-enabled=true

          [org/gnome/desktop/session]
          # Set the lock time out to 900 seconds before the session is considered idle
          idle-delay=uint32 900

  ignore_errors: yes
  tags:
    - gui_setup
    - 'xxxxx'


- name: "V-xxxx -- create /etc/dconf/db/local.d/locks/session..."
  file:
    path: /etc/dconf/db/local.d/locks/session
    state: touch
  ignore_errors: yes
  tags:
    - gui_setup
    - 'xxxxx'

- name: "V-xxxxx -- setup screensaver data to 00-screensaver file..."
  blockinfile:
     path: /etc/dconf/db/local.d/locks/session
     block: |
          /org/gnome/desktop/screensaver/idle-activation-enabled
          /org/gnome/desktop/screensaver/lock-delay
  ignore_errors: yes
  tags:
    - gui_setup
    - 'xxxxx'

- name: "Restart dconf..."
  shell: dconf update
  ignore_errors: yes

...

