---

# tasks file for encrypt_root_pw

- name: "copy python script for grub2 mkpasswd..."
  copy:
     src: /home/hcsdadm/cns-ssa/ansible/stigs/roles/encrypt_root_pw/files/encrypt_passwd.py
     dest: /home/cnsauto
     mode: u=rwx,g=x,o=x
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'


- name: "run the grub2 python script..."
  command: python /home/cnsauto/encrypt_passwd.py
  register: rsp
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'

- name: "Get the hash encrypted password for root..."
  set_fact: found_hash="{{ rsp.stdout | regex_search('(grub\.pbkdf2\.sha512[.0-9A-Z]+)') }}"
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'

- debug: msg="{{ found_hash }}"
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'

- name: "Edit /etc/grub.d/40_custom with new password hash for root"
  blockinfile:
     path: /etc/grub.d/40_custom
     block: |
       set superusers="root"
       password_pbkdf2 root {{ found_hash }}
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'

- name: "create the new grub.conf with new password, grub2-mkconfig"
  shell: grub2-mkconfig --output=/tmp/grub2.cfg
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'

- name: "check for directory, create if needed /boot/efi..."
  file:
     path: /boot/efi
     state: directory
     mode: 0755
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'

- name: "check for directory, create if needed /boot/efi/EFI..."
  file:
     path: /boot/efi/EFI
     state: directory
     mode: 0755
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'

- name: "check for directory, create if needed /boot/efi/EFI/redhat..."
  file:
     path: /boot/efi/EFI/redhat
     state: directory
     mode: 0755
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'

- name: "move grub2.cfg to /boot/efi/EFI/redhat/grub.cfg..."
  shell: mv /tmp/grub2.cfg  /boot/efi/EFI/redhat/grub.cfg
  ignore_errors: yes
  tags:
    - enrootpw_setup
    - '71963'

- set_fact: var1="{{found_hash.split('grub.pbkdf2.sha512') }}"
  tags:
    - enrootpw_setup
    - '71963'

- name: "Create value for user.cfg..."
  set_fact: mmsg="{{ 'GRUB2_PASSWORD=grub.pbkdf2.sha512'}}{{ var1[1] }}"
  tags:
    - enrootpw_setup
    - '71963'

- name: "create file /boot/efi/EFI/redhat/user.cfg"
  file:
      path: /boot/efi/EFI/redhat/user.cfg
      state: touch
  tags:
    - enrootpw_setup
    - '71963'

- name: "V-72187 -- add to user.cfg..."
  lineinfile:
      path: /boot/efi/EFI/redhat/user.cfg
      line: "{{ mmsg }}"
  tags:
    - enrootpw_setup
    - '71963'

...

