---

# Version 1.0
# tasks file for winServ12_CertEnrollPolicyWebServ

- name: "Get the Certificate Thumbprint"
  win_shell: Get-ChildItem Cert:\LocalMachine\my
  register: thumbprint_results
  ignore_errors: True   

- set_fact: ca_thumbprint="{{ item }}"
  with_items: "{{ thumbprint_results.stdout_lines }}"
  when: item | search(ad_domain.domain)

- name: "Parse out certificate thumbprint for server"
  set_fact: found_thumbprint="{{ ca_thumbprint | regex_search('(^[\d\w]+)') }}"

- debug: msg="Found thumbprint - {{ found_thumbprint }} "
  when: found_thumbprint is defined

- fail: msg="Failed to find thumbprint for certificate server"
  when: found_thumbprint is undefined

- name: "Setup Enrollment Policy Web Service"
  script: CreateEnrollPolicyWebService.ps1 -thumbprint "{{ found_thumbprint }}" -safe_passwd "{{ safe_passwd }}" -safe_domain_nm "{{ safe_domain_nm }}" -domain "{{ ad_domain.domain }}"

...
