---
# tasks file for ssh_config

- name: "V-72257 -- chmod on files /etc/ssh/ssh_host*key"
  shell: chmod 0600 /etc/ssh/ssh_host*key
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72257'

- name: "V-72267 -- Uncomment compression delayed in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: '#Compression delayed'
     replace: 'Compression no'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72267'

- name: "V-72263 -- Uncomment StrictModes in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: '#StrictModes yes'
     replace: 'StrictModes yes'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72263'

- name: "V-72259 -- Modify GSSAPIAuthentication in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: 'GSSAPIAuthentication yes'
     replace: 'GSSAPIAuthentication no'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72259'

- name: "V-71959 -- Uncomment hostbasedauthentication in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: '#HostbasedAuthentication no'
     replace: 'HostbasedAuthentication no'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '71959'

- name: "V-72249 -- Uncomment IgnoreUserKnownHosts in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: '#IgnoreUserKnownHosts no'
     replace: 'IgnoreUserKnownHosts yes'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72249'

- name: "V-72247 -- Remove PermitRootLogin in /etc/ssh/sshd_config"
  blockinfile:
      path: /etc/ssh/sshd_config
      marker: "#PermitRootLogin yes"
      content: ""
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72247'

- name: "V-72245 -- uncomment printlastlog in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: '#PrintLastLog yes'
     replace: 'PrintLastLog yes'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72245'

- name: "V-72243 -- uncomment IgnoreRhosts in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: '#IgnoreRhosts yes'
     replace: 'IgnoreRhosts yes'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72243'

- name: "V-72239 -- uncomment RhostsRSAAuthentication in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: '#RhostsRSAAuthentication no'
     replace: 'RhostsRSAAuthentication no'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72239'

- name: "V-72237 -- set ClientAliveInterval to 600 in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: 'ClientAliveInterval 900'
     replace: 'ClientAliveInterval 600'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72237'

- name: "V-72261 -- uncomment KerberosAuthentication in /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: '#KerberosAuthentication no'
     replace: 'KerberosAuthentication no'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72261'

- name: "V-72253 -- remove hmac-sha1 from line MACs in /etc/ssh/sshd_config"
  lineinfile:
     path: /etc/ssh/sshd_config
     regexp: '^MACs.*'
     line: 'MACs hmac-sha2-256,hmac-sha2-512'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72253'

- name: "V-72303 -- change X11Forwarding yes from /etc/ssh/sshd_config"
  replace:
     path: /etc/ssh/sshd_config
     regexp: '#X11Forwarding yes'
     replace: 'X11Forwarding yes'
  ignore_errors: yes
  tags:
     - ssh_setup
     - '72303'

- name: "V-72221 -- remove all cbc ciphers from line Ciphers in /etc/ssh/sshd_config"
  lineinfile:
     path: /etc/ssh/sshd_config
     regexp: '^Ciphers.*'
     line: 'Ciphers aes128-ctr,aes192-ctr,aes256-ctr'
  ignore_errors: yes
  tags:
    - ssh_setup
    - '72221'

- name: "wait 5 seconds before restarting sshd ..."
  pause:
    seconds: 5
  tags:
    - ssh_setup


- name: "Restart sshd..."
  shell: systemctl restart sshd
  register: resp
  ignore_errors: yes

- debug: msg="{{resp}}"
  tags:
     - ssh_setup

- name: "wait 10 seconds after restarting sshd ..."
  pause:
    seconds: 10
  tags:
    - ssh_setup

...

